version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
skip_commits:
  files:
    - docs/*
    - '**/*.md'
