version: 1.5.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
skip_commits:
  files:
    - docs/*
    - '**/*.md'
artifacts:
- path: NuGet/Release/EntityFramework.Guardian.Core.*.nupkg
- path: NuGet/Release/EntityFramework.Guardian.Entities.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 5VFC2Dd+/TtE6KO8MeJyA8Oey2ACijjLFC71tGkkBg5P7/Con1yEPCCPrFbUpDPR
